# Generated by Django 4.2.13 on 2025-02-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_liked_by_recipe_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
